# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=30)),
                ('contacts', models.PositiveIntegerField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('neighborhood_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update.Neighborhood')),
            ],
        ),
    ]
