# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0002_emergencycontacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontacts',
            name='contacts',
            field=models.PositiveIntegerField(),
        ),
    ]
