# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0003_auto_20181125_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=30)),
                ('contacts', models.PositiveIntegerField()),
                ('hospital', models.CharField(max_length=50)),
                ('neighborhood_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update.Neighborhood')),
            ],
        ),
        migrations.RemoveField(
            model_name='emergencycontacts',
            name='neighborhood_contact',
        ),
        migrations.DeleteModel(
            name='EmergencyContacts',
        ),
    ]
