# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0004_auto_20181125_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Station', models.CharField(max_length=30)),
                ('contacts', models.PositiveIntegerField()),
                ('neighborhood_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update.Neighborhood')),
            ],
        ),
    ]
